name: CI
on: [push,workflow_dispatch]

jobs:     
  test-with-torque:
    runs-on: ubuntu-latest
    
    steps:
    - name: Start Torque Sandbox
      id: start-sandbox
      uses: QualiTorque/torque-start-sb-action@v0.0.3
      with:
        space: Trial
        blueprint_name: Dev & Test Environment (All-in-One, Azure)
        torque_token: ${{ secrets.TORQUE_TOKEN }}
        duration: 120
        timeout: 30
