---
spec_version: 1
kind: blueprint

metadata:
  description: >
    A simple multi-tier application deployed on a single Azure VM.
clouds:
  - azure: westeurope

# These are the applications that will be deployed in this blueprint
applications:
  - mysql:  # One instance of mysql (see: applications/mysql/mysql.yaml)
      target: all-in-one
      input_values:
        - DB_USER: root
        - DB_PASS: 12345
        - DB_NAME: demo_db
  # One instance of java-spring-website
  # (see: applications/java-spring-website/java-spring-website.yaml)
  - java-spring-website:
      target: all-in-one
      input_values:
        - DB_USER: root
        - DB_PASS: 12345
        - DB_NAME: demo_db
      # The website depends on MySQL and will start deploying only when
      # the database is ready
      depends_on:
        - mysql
